import flet as ft

def build_terms_page(page: ft.Page):
    return ft.View(
        "/terms",
        [
            ft.AppBar(
                bgcolor=ft.colors.BLUE_GREY_900,
                leading=ft.IconButton(
                    icon=ft.icons.ARROW_BACK,
                    on_click=lambda _: page.go("/")
                )
            ),
            ft.Container(
                content=ft.Container(
                    content=ft.Column(
                        [
                            ft.Text(
                                "Terms of Service",
                                style=ft.TextStyle(
                                    size=32,
                                    weight=ft.FontWeight.BOLD
                                )
                            ),
                            ft.Container(
                                content=ft.Text(
                                    """
                                    Introduction and Definitions
                                    Welcome to Weigh In ("we," "us," "our," or the "Company"), a Software-as-a-Service (SaaS) platform that facilitates group decision-making using advanced algorithms. These Terms of Service ("Terms") govern your access to and use of the Weigh In website, applications, and related services (collectively, the "Platform").
                                    For the purposes of these Terms:

                                    "Weigh In" refers to the Company, its officers, directors, employees, and agents.
                                    "User," "you," or "your" refers to any individual or entity accessing or using the Platform.
                                    "Decision-Maker (DM)" refers to a User participating in group decision-making processes on the Platform.
                                    "Group Decision" refers to the collective outcome derived from inputs provided by multiple DMs.
                                    By accessing or using the Platform, you agree to these Terms. If you do not agree, do not use the Platform.

                                    Eligibility
                                    You must be at least 18 years old or the age of majority in your jurisdiction to use the Platform. By using Weigh In, you represent and warrant that you meet this requirement.
                                    Platform Features and Responsibilities
                                    3.1. Weigh In's Role:
                                    We provide tools for group decision-making using advanced multi-criteria methodologies like the HIVES algorithm. We do not take responsibility for decisions made based on outputs generated by the Platform.
                                    3.2. User Responsibility:
                                    Users are responsible for ensuring that the criteria and inputs they provide are accurate, relevant, and lawful.

                                    3.3. Service Availability:
                                    Weigh In reserves the right to modify, suspend, or discontinue any part of the Platform at any time without prior notice.

                                    Account Registration and Security
                                    4.1. You may need to register for an account to access certain features.
                                    4.2. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.
                                    4.3. You agree to provide accurate and complete information during registration and keep it up-to-date.
                                    Use of the Platform
                                    5.1. You agree to use the Platform for lawful purposes only.
                                    5.2. Prohibited activities include, but are not limited to:
                                    Submitting false or misleading inputs.
                                    Attempting to manipulate group outcomes unfairly.
                                    Engaging in activities that disrupt the Platform or its Users.
                                    Privacy and Data
                                    We respect your privacy. Your use of the Platform is subject to our Privacy Policy, which outlines how we collect, store, and process data.
                                    Intellectual Property
                                    The Platform and its contents, including but not limited to text, algorithms, graphics, and software, are owned by Weigh In or its licensors and are protected by intellectual property laws. You may not copy, modify, or distribute any part of the Platform without prior written consent.
                                    Limitations of Liability
                                    8.1. The Platform is provided "as is" without warranties of any kind.
                                    8.2. Weigh In is not liable for any indirect, incidental, or consequential damages arising from your use of the Platform, including decisions made using its outputs.
                                    Modifications to Terms
                                    Weigh In reserves the right to modify these Terms at any time. We will notify you of significant changes, and continued use of the Platform constitutes acceptance of updated Terms.
                                    Governing Law
                                    These Terms are governed by and construed in accordance with the laws of [Your Jurisdiction].
                                    Contact Us
                                    For questions about these Terms, please contact us at support@weighin.app.
                                    Last updated: January 15, 2025

                                    © 2025 Weigh In. All Rights Reserved.
                                    """,
                                    style=ft.TextStyle(
                                        size=16,
                                        weight=ft.FontWeight.NORMAL
                                    )
                                ),
                                expand=True
                            )
                        ],
                        alignment=ft.MainAxisAlignment.CENTER,
                        spacing=20,
                        scroll=ft.ScrollMode.AUTO,
                        expand=True
                    ),
                    alignment=ft.alignment.center,
                    expand=True
                ),
                expand=True
            ),
        ]
    )